language java
jdk: oraclejdk8
install: true
addons:
  sonarcloud:
    organization: "ducthang1410"
    token:
      secure: "7e45fc0511d8b8ff1e2fb803bebf05ddb3761520" # encrypted value of your token

script:
  ./gradlew clean check build
cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle